default:
  image: debian:buster
  before_script:
    - apt-get update
    - apt-get install -y util-linux binutils coreutils pylint lsb-release python3 python3-psutil python3-mysqldb python3-sphinx dvipng imagemagick-6.q16 latexmk sphinx-doc libjs-mathjax texlive-fonts-recommended texlive-latex-base texlive-latex-recommended texlive-latex-extra xzdec
    - python3 --version
    - lsb_release -a

stages:
    - Static Analysis
    - Tests
    - Doc Generation

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - ls -l
    - for file in `find . -iname "*.py"`; do pylint $file || FAILED=true; done
    - exit 0


pyunit:
  stage: Tests
  script:
    - cd Testing/Software/
    - ls -l
    - python3 ./unittests.py -a

sphinx:
  stage: Doc Generation
  script:
    - cd docs
    - make html
    - make epub
    - make latexpdf
